### ISSUE TITLE
drinks (juices) causing damage.

### ISSUE THREAD

**Issue by MeseCraft** [MeseCraft/MeseCraft#56]
After https://github.com/MeseCraft/MeseCraft/commit/5c21717ed27ce11b7a3edcffb26efbced1d505eb was merged, drinks are now causing damage to health (life bar) on drink. @AndyIII

**Comment by AndyIII** [comment]
You are right, I missed this because I was wearing armor. The hbhunger mod tests "poisen" as a boolean (where 0 == true) before poisoning the player for "poisen" seconds. I was defaulting to 0 so that I could multiply by the size of the container you were drinking. So basically, all juice became a minor poison.

**Comment by MeseCraft** [comment]
fixed in https://github.com/MeseCraft/MeseCraft/pull/57
